### ISSUE TITLE
Не фильтруются ошибочные форматы.

### ISSUE THREAD

**Issue by clicman** [m01ten/testArithmeticProject#2]
Если поставить строку 1;1;2;3 в начало файла, выдастся, что все тесты пройдены. А ошибку не покажет.

**Comment by m01ten** [comment]
В требованиях написано "operation - арифметическое действие + - / *", поэтому проверять не стал. Переделаю.
Еще написано "operand1 и operand2 - операнды, целые числа". Нужно закладываться на то,что там может быть что угодно?
